export const CAROUSEL_CONFIG = {
    RADIUS: 3,
    ANGLE_STEP: 0.8,
    VERTICAL_STEP: -0.4,
    SCALE_FACTOR: 1.5,

    LERP_SPEED: 0.12,
    SCROLL_SENSITIVITY: 0.0008,
    SCROLL_DAMPING: 0.15,
    SCROLL_DEADZONE: 0.0001,

    SCALE_RANGE: 0.3,

    CARD_GAP_FACTOR: 0.99,
    CARD_ASPECT: 16 / 9,

    CAMERA: {
        POSITION: [0, 0, 8],
        FOV: 50,
    }
};
